[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
lib_deps =
    ssilverman/QNEthernet
    greiman/SdFat
upload_protocol = teensy-cli
monitor_speed = 115200
monitor_port = /dev/ttyACM0
